dataset_args:
  ctf: /usr/scratch/CryoEM/CryoSensing/empiar10076/diffusion/data_128/val_test_ctf.pkl
  datadir: null
  do_pose_sgd: false
  ind: null
  invert_data: false
  keepreal: false
  norm:
  - 0.0
  - 33.03333282470703
  particles: /usr/scratch/CryoEM/CryoSensing/empiar10076/diffusion/data_128/dps_reconstruction_val_test_128_bs16_masks204_normalized_minus1to1.mrcs
  poses: /usr/scratch/CryoEM/CryoSensing/empiar10076/diffusion/data_128/val_test_poses.pkl
  window: true
  window_r: 0.85
lattice_args:
  D: 129
  extent: 0.5
  ignore_DC: true
model_args:
  activation: relu
  domain: fourier
  enc_mask: 64
  encode_mode: resid
  feat_sigma: 0.5
  pdim: 1024
  pe_dim: null
  pe_type: gaussian
  players: 3
  qdim: 1024
  qlayers: 3
  tilt_params:
    ntilts: 10
    t_emb_dim: 64
    tdim: 1024
    tlayers: 3
  zdim: 8
seed: 60538
time: 2025-05-08 20:38:52.185741
version: 3.4.0
